By default don't touch already formatted files

diff --git a/hs-format b/hs-format
--- a/hs-format
+++ b/hs-format
@@ -1,6 +1,11 @@
 #!/bin/bash
 
+usage () {
+echo usage: "$0" "[--check | --force]"
+}
+
 check_only=
+force=
 
 while [[ $# -gt 0 ]]
 do
@@ -11,11 +16,23 @@ case $key in
     check_only=1
     shift
     ;;
-    *)
+    --force)
+    force=1
     shift
+    ;;
+    *)
+    echo "$0": unknown option: "$1"
+    usage
+    exit
     ;;
 esac
 done
+
+if [[ -n $check_only && -n $force ]]; then
+    echo "$0": --check cannot be used with --force
+    usage
+    exit
+fi
 
 extensions=(hs lhs)
 git_flags=(--cached --others --exclude-standard)
@@ -26,6 +43,13 @@ if [[ -n $check_only ]]; then
     exit
 fi
 
+if [[ -n $force ]]; then
+    git ls-files -z "${git_flags[@]}" "${patterns[@]}" |
+    xargs -0 printf -- ' "%s"\n' |
+    xargs ormolu --mode=inplace
+    exit
+fi
+
 git ls-files -z "${git_flags[@]}" "${patterns[@]}" |
-xargs -0 printf -- ' "%s"\n' |
-xargs ormolu --mode=inplace
+xargs -0 -I % bash -c 'ormolu --mode=check "%" || echo \"%\"' |
+xargs -I % ormolu --mode=inplace %
